package crypto_test

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	sdkcrypto "github.com/cosmos/cosmos-sdk/crypto"
)

// Historical vectors are generated by the unmodified SDK v0.54.4. They contain
// only synthetic test material. The generator and original dynamic oracle are
// preserved in the Xitcoin qualification evidence; production never imports it.
func TestHistoricalArmorCompatibility(t *testing.T) {
	var fixture struct {
		Synthetic       bool
		GeneratorSDK    string
		GeneratorCommit string
		PublicKey       []byte
		Vectors         []struct {
			Type    string
			Headers map[string]string
			Payload []byte
			Encoded string
		}
	}
	data, err := os.ReadFile("testdata/historical_armor.json")
	require.NoError(t, err)
	require.NoError(t, json.Unmarshal(data, &fixture))
	require.True(t, fixture.Synthetic)
	require.Len(t, fixture.Vectors, 15)
	require.Equal(t, "github.com/cosmos/cosmos-sdk v0.54.4", fixture.GeneratorSDK)
	require.Equal(t, "dedeb7c80a91c47ae83f5352e29c3dd34e4a3fc6", fixture.GeneratorCommit)

	for i, vector := range fixture.Vectors {
		t.Run(fmt.Sprintf("%s-%d", vector.Type, i), func(t *testing.T) {
			kind, headers, payload, err := sdkcrypto.DecodeArmor(vector.Encoded)
			require.NoError(t, err)
			require.Equal(t, vector.Type, kind)
			require.Len(t, headers, len(vector.Headers))
			for key, value := range vector.Headers {
				require.Equal(t, value, headers[key])
			}
			require.Equal(t, vector.Payload, payload)
			// Header order is unspecified for maps with multiple entries. The
			// zero/single-header vectors check the legacy writer byte for byte,
			// including CRC and line wrapping at boundary payload sizes.
			if len(vector.Headers) <= 1 {
				require.Equal(t, vector.Encoded, sdkcrypto.EncodeArmor(vector.Type, vector.Headers, vector.Payload))
			}
			switch vector.Type {
			case "TENDERMINT PUBLIC KEY":
				got, algo, err := sdkcrypto.UnarmorPubKeyBytes(vector.Encoded)
				require.NoError(t, err)
				require.Equal(t, "secp256k1", algo)
				require.Equal(t, fixture.PublicKey, got)
			case "TENDERMINT KEY INFO":
				got, err := sdkcrypto.UnarmorInfoBytes(vector.Encoded)
				require.NoError(t, err)
				require.Equal(t, vector.Payload, got)
			}
		})
	}
	for _, bad := range []string{"", "not armor", "-----BEGIN TENDERMINT PRIVATE KEY-----\n\ninvalid!\n-----END TENDERMINT PRIVATE KEY-----"} {
		_, _, _, err := sdkcrypto.DecodeArmor(bad)
		require.Error(t, err)
	}
}

// Corruption must fail before decoding a key, even when its payload remains
// syntactically valid. Preambles and subsequent blocks must not select the CRC.
func TestArmorChecksumCompatibility(t *testing.T) {
	valid := sdkcrypto.EncodeArmor("TENDERMINT PUBLIC KEY", nil, []byte("payload"))
	checksum := strings.LastIndex(valid, "\n=")
	require.GreaterOrEqual(t, checksum, 0)
	beforeEnd, _, found := strings.Cut(valid, "-----END")
	require.True(t, found)
	cases := []struct {
		name, input string
		valid       bool
	}{
		{"valid", valid, true},
		{"corrupt payload", strings.Replace(valid, "cGF5bG9hZA==", "cGF5bG9hZQ==", 1), false},
		{"corrupt checksum", valid[:checksum+2] + "AAAA" + valid[checksum+6:], false},
		{"missing end", beforeEnd, false},
		{"no checksum", valid[:checksum] + valid[checksum+6:], true},
		{"leading garbage", "=AAAA\nignored\n" + valid, true},
		{"following block", valid + "\n" + strings.Replace(valid, "cGF5bG9hZA==", "cGF5bG9hZQ==", 1), true},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, _, _, err := sdkcrypto.DecodeArmor(tc.input)
			if tc.valid {
				require.NoError(t, err)
			} else {
				require.Error(t, err)
			}
		})
	}
}
